### ISSUE TITLE
v1.1.2 improve action log visually

### ISSUE THREAD

**Issue by nobruinfo** [MoDuLah/TDU2-SaveGame-Manager#3]
Testing this version I found no errors. Backup and restore work just great in default and user chosen folders. All the options and the changed GUI work just fine.
There is one minor GUI issue. As the *action log* gets longer and its entries contain longer texts it gets sort of visually nasty:
![grafik](https://github.com/user-attachments/assets/e603b71e-08b8-4cbd-8a8b-3180ddd1dde9)
This could maybe be something you want to improve on. Thank you.

**Comment by MoDuLah** [comment]
This has already been addressed by moving the action log to the main window and giving it larger space to report in. Maybe in a future version I will make a toggle in the settings as it there won't be a need for it. (once we  achieve 100% functionality).
