### ISSUE TITLE
v1.1.2 .tar files are off standard

### ISSUE THREAD

**Issue by nobruinfo** [MoDuLah/TDU2-SaveGame-Manager#4]
An observation for users maybe wanting to directly work with the by TDU2-SaveGame-Manager created .tar files is that the new library makes strange and off-standard file entries. Upon unpackiging this creates single level file entries in Explorer which would make it difficult to restore the original folder structure should users prefer to do this manually:
![grafik](https://github.com/user-attachments/assets/415b8ee1-b40b-4c48-9cb4-f0877db4cc3a)
and
![grafik](https://github.com/user-attachments/assets/e18635bc-8781-4e6c-a205-b753fcdee9f3)
Thank you for considering.

**Comment by MoDuLah** [comment]
That issue has been noticed from 7zip users. 7zip seems to be the problem.
Anyway in order to make everyone's life easier, I have switched the archiving format to zip. This way even users without any archive software will be able to access their saves without the need for this software.
