### ISSUE TITLE
v1.1.2 Feature request for compressed backup files

### ISSUE THREAD

**Issue by nobruinfo** [MoDuLah/TDU2-SaveGame-Manager#5]
Me again. On second thoughts I still think there could be a user option to change from uncompressed .tar backup files to compressed .tgz or .zip backups to lower disk usage. You could of course leave this off by default to maintain current behaviour. Thank you for your consideration and all the effort brought into this project.

**Comment by MoDuLah** [comment]
That can be implemented in the future. Another possibility is to keep the latest 5 backups. But that's for the future.
Currently the scope doesn't include compression. Just storage.

**Comment by nobruinfo** [comment]
You could keep the ticket open as a reminder then. I won't put pressure on you only because it remains open for months. ;)
